events {}
http {
    server {
        listen 80;
        location / {
            # No spaces in the MIME type
            default_type text/plain; 
            # Clean string with a semicolon at the end
            return 200 "Hello from my Custom Container!\n";
        }
    }
}
